---
title: "chp-2 - trash"
author: "paulo"
date: "2025-08-16"
output: html_document
---
#### Display the first two right singular vectors

```{r , include=TRUE, fig.width = 9}
# ───── Display the first two right singular vectors─────────────────────────────

# In place of the scale function, the mean curve was subtracted. 
# This approach facilitates comparison with the variable W as presented in the book, 
#and ultimately yields an equivalent result.
centered_states_cum_tf <- states_cum_tf - mean_curve

# FPCA
covid_pc <- tfb_fpc(centered_states_cum_tf, pve = 0.99)
# tfb[52] on (0,357) in basis representation:
#  using  4 FPCs 
# [1]: ( 0,-1.2);( 7,-0.4);(14,-1.6); ...
# [2]: ( 0,  -5);( 7,  -5);(14,  -8); ...
# [3]: ( 0,  -4);( 7,  -3);(14,  -8); ...
# [4]: ( 0,-0.6);( 7,-0.7);(14,-1.5); ...
# [5]: ( 0,  -4);( 7,  -3);(14,  -5); ...
#     [....]   (47 not shown)

basis_functions <- tf_basis(covid_pc, as_tfd = TRUE)
# tfd[5] on (0,357) based on 52 evaluations each
# interpolation by tf_approx_linear 
# [1]: ( 0, 5e-16);( 7, 1e-16);(14, 1e-15); ...
# [2]: ( 0, 3e-04);( 7, 3e-04);(14, 3e-04); ...
# [3]: ( 0,-6e-04);( 7,-9e-04);(14,-2e-03); ...
# [4]: ( 0,-0.003);( 7,-0.001);(14,-0.003); ...
# [5]: ( 0,-0.004);( 7,-0.010);(14,-0.023); ...



ggplot() +
  geom_spaghetti(aes(y = basis_functions[2]),
                 colour = "coral", alpha = 2) +
  geom_spaghetti(aes(y = basis_functions[3]),
                 colour = "coral4", alpha = 2) +
  scale_x_continuous(
    name = "Weeks starting January 2020",
    breaks = as.numeric(seq(reference_date, as.Date("2021-01-01"), by = "3 months") - reference_date),
    labels = format(seq(reference_date, as.Date("2021-01-01"), by = "3 months"), "%b %Y")
  ) +
  labs(
    x = "Weeks starting January 2020",
    y = "Eigenfunctions"
  ) +
  theme_classic(base_size = 13)
# # ───── Book's approach for comparison(manual svd approach)─────────────────────────────
# 
#Construct the de-meaned data. The columns of W have mean zero
W <- scale(cum_mat, center = TRUE, scale = FALSE)
# SVD
svd_W <- svd(W)
# Eigenfunctions (right singular vectors)
V <- svd_W$v



# # ───── Plot(Comparison)─────────────────────────────
# #Display the first two right singular vectors
# 
# par(mar = c(5, 4, 4, 8) + 0.1,
#     xpd = TRUE)    
# 
# 
# plot(num_grid(current_date), V[,1], type="l", col="coral", lwd=2.5,
#      ylab="Eigenfunctions", xlab="2020 calendar year (in days)",
#      ylim = c(-0.35, 0.35), 
#      cex=1, bty="n")
# 
# # FPCA PC1
# lines(basis_functions[2],   col="coral",  lwd=2, lty=2)   
# # SVD PC2
# lines(num_grid(current_date), V[,2],      col="coral4", lwd=2) 
# # FPCA PC2
# lines(basis_functions[3],   col="coral4", lwd=2, lty=2)   
# 
# 
# legend("topright",
#        legend = c("SVD PC1", "FPCA PC1", "SVD PC2", "FPCA PC2"),
#        col = c("coral", "coral", "coral4", "coral4"),
#        lty = c(1, 2, 1, 2),
#        lwd = 2,
#        bty = "n",
#        cex = 0.7,
#        # Two columns to save space
#        ncol = 2)  
```

```{r , include=TRUE}

```

According to the book, the analysis relies on a rank $K_0=2$ reconstruction, a method that explains 95.9% of the variability within the de-meaned data.

```{r , include=TRUE, fig.width=15}
# ──────────────────── Compare the real and reconstructed data ──────────────────────
#Book approach for comparison later
# mW <- colMeans(cum_mat)
# 
# #Construct a matrix of same dimension as cum_mat with the mean of cum_mat on each row
# mW_mat <- matrix(rep(mW, each = nrow(cum_mat)), ncol = ncol(cum_mat))
# 
# 
# 
# # Manual reconstruction (K = 2)
# K0 <- 2
# rec <- svd_W$u[,1:K0] %*% diag(svd_W$d[1:K0]) %*% t(V[,1:K0])
# WK0 <- mW_mat + rec



# Manual SVD reconstruction as tfd
#manual_svd <- tfd(WK0, arg = num_grid(current_date), id = new_states, var = "cum_excess")
# tfd[52] on (0,357) based on 52 evaluations each
# interpolation by tf_approx_linear 
# [1]: ( 0, 9);( 7,15);(14,22); ...
# [2]: ( 0, 2);( 7, 7);(14,10); ...
# [3]: ( 0, 9);( 7,15);(14,22); ...
# [4]: ( 0, 7);( 7,14);(14,22); ...
# [5]: ( 0, 4);( 7,10);(14,13); ...
#     [....]   (47 not shown)


#Uses functional principal components
svd_tfb <- tfb_fpc(states_cum_tf, pve = .9)
# tfb[52] on (0,357) in basis representation:
#  using  2 FPCs 
# [1]: ( 0, 9);( 7,15);(14,22); ...
# [2]: ( 0, 2);( 7, 7);(14,10); ...
# [3]: ( 0, 9);( 7,15);(14,22); ...
# [4]: ( 0, 7);( 7,14);(14,22); ...
# [5]: ( 0, 4);( 7,10);(14,13); ...
#     [....]   (47 not shown)





emphasize <- c("New Jersey", "Louisiana", "California", "Maryland", "Texas")
emph_cols <- c("plum3","red", "deepskyblue4","darkseagreen3", "salmon")

# Create comparison data frame
comp_df <- tibble(
  state = new_states,
  original_curve = states_cum_tf,
  #recon_manual = manual_svd,      # Manual SVD reconstruction
  recon_tfb = svd_tfb            # tfb_fpc reconstruction
) %>%
  filter(state %in% emphasize)

# ───── Plot ────────────────────────────────────


# Original vs Manual SVD reconstruction 

# p1 <- ggplot(comp_df) +
#   geom_spaghetti(aes(y = original_curve, color = state),
#                  linewidth = 2, alpha = 0.8) +
#   geom_spaghetti(aes(y = recon_manual, color = state),
#                  linewidth = 2, linetype = "dashed", alpha = 0.8) +
#   scale_color_manual(values = emph_cols) +
#   scale_x_continuous(
#     name = "Weeks starting January 2020",
#     breaks = as.numeric(seq(reference_date, as.Date("2021-01-01"), by = "3 months") - reference_date),
#     labels = format(seq(reference_date, as.Date("2021-01-01"), by = "3 months"), "%b %Y")
#   ) +
#   labs(
#     title = "Manual SVD  (K=2)",
#     x = "Weeks starting January 2020",
#     y = "Cumulative excess deaths per million",
#     color = NULL
#   ) +
#   theme_classic(base_size = 14)

#Original vs tfb_fpc 
p2 <- ggplot(comp_df) +
  geom_spaghetti(aes(y = original_curve, color = state),
                 linewidth = 2, alpha = 0.8) +
  geom_spaghetti(aes(y = recon_tfb, color = state),
                 linewidth = 2, linetype = "dashed", alpha = 0.8) +
  scale_color_manual(values = emph_cols) +
  scale_x_continuous(
    name = "Weeks starting January 2020",
    breaks = as.numeric(seq(reference_date, as.Date("2021-01-01"), by = "3 months") - reference_date),
    labels = format(seq(reference_date, as.Date("2021-01-01"), by = "3 months"), "%b %Y")
  ) +
  labs(
    title = "tfb_fpc Reconstruction",
    x = "Weeks starting January 2020",
    y = "Cumulative excess deaths per million",
    color = NULL
  ) +
  theme_classic(base_size = 14)

# Display plots

#grid.arrange(p1 , p2, ncol=2)
p2

```
